// Generated by gencpp from file itr_rpc/IK_Solve.msg
// DO NOT EDIT!


#ifndef ITR_RPC_MESSAGE_IK_SOLVE_H
#define ITR_RPC_MESSAGE_IK_SOLVE_H

#include <ros/service_traits.h>


#include <itr_rpc/IK_SolveRequest.h>
#include <itr_rpc/IK_SolveResponse.h>


namespace itr_rpc
{

struct IK_Solve
{

typedef IK_SolveRequest Request;
typedef IK_SolveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IK_Solve
} // namespace itr_rpc


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::itr_rpc::IK_Solve > {
  static const char* value()
  {
    return "39b92dc189c60778ee4cbbd09d427326";
  }

  static const char* value(const ::itr_rpc::IK_Solve&) { return value(); }
};

template<>
struct DataType< ::itr_rpc::IK_Solve > {
  static const char* value()
  {
    return "itr_rpc/IK_Solve";
  }

  static const char* value(const ::itr_rpc::IK_Solve&) { return value(); }
};


// service_traits::MD5Sum< ::itr_rpc::IK_SolveRequest> should match
// service_traits::MD5Sum< ::itr_rpc::IK_Solve >
template<>
struct MD5Sum< ::itr_rpc::IK_SolveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::itr_rpc::IK_Solve >::value();
  }
  static const char* value(const ::itr_rpc::IK_SolveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::itr_rpc::IK_SolveRequest> should match
// service_traits::DataType< ::itr_rpc::IK_Solve >
template<>
struct DataType< ::itr_rpc::IK_SolveRequest>
{
  static const char* value()
  {
    return DataType< ::itr_rpc::IK_Solve >::value();
  }
  static const char* value(const ::itr_rpc::IK_SolveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::itr_rpc::IK_SolveResponse> should match
// service_traits::MD5Sum< ::itr_rpc::IK_Solve >
template<>
struct MD5Sum< ::itr_rpc::IK_SolveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::itr_rpc::IK_Solve >::value();
  }
  static const char* value(const ::itr_rpc::IK_SolveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::itr_rpc::IK_SolveResponse> should match
// service_traits::DataType< ::itr_rpc::IK_Solve >
template<>
struct DataType< ::itr_rpc::IK_SolveResponse>
{
  static const char* value()
  {
    return DataType< ::itr_rpc::IK_Solve >::value();
  }
  static const char* value(const ::itr_rpc::IK_SolveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ITR_RPC_MESSAGE_IK_SOLVE_H
