// Generated by gencpp from file itr_rpc/PointCollision.msg
// DO NOT EDIT!


#ifndef ITR_RPC_MESSAGE_POINTCOLLISION_H
#define ITR_RPC_MESSAGE_POINTCOLLISION_H

#include <ros/service_traits.h>


#include <itr_rpc/PointCollisionRequest.h>
#include <itr_rpc/PointCollisionResponse.h>


namespace itr_rpc
{

struct PointCollision
{

typedef PointCollisionRequest Request;
typedef PointCollisionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PointCollision
} // namespace itr_rpc


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::itr_rpc::PointCollision > {
  static const char* value()
  {
    return "c20cdc77e4139edffff4d2a510fde4fb";
  }

  static const char* value(const ::itr_rpc::PointCollision&) { return value(); }
};

template<>
struct DataType< ::itr_rpc::PointCollision > {
  static const char* value()
  {
    return "itr_rpc/PointCollision";
  }

  static const char* value(const ::itr_rpc::PointCollision&) { return value(); }
};


// service_traits::MD5Sum< ::itr_rpc::PointCollisionRequest> should match
// service_traits::MD5Sum< ::itr_rpc::PointCollision >
template<>
struct MD5Sum< ::itr_rpc::PointCollisionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::itr_rpc::PointCollision >::value();
  }
  static const char* value(const ::itr_rpc::PointCollisionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::itr_rpc::PointCollisionRequest> should match
// service_traits::DataType< ::itr_rpc::PointCollision >
template<>
struct DataType< ::itr_rpc::PointCollisionRequest>
{
  static const char* value()
  {
    return DataType< ::itr_rpc::PointCollision >::value();
  }
  static const char* value(const ::itr_rpc::PointCollisionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::itr_rpc::PointCollisionResponse> should match
// service_traits::MD5Sum< ::itr_rpc::PointCollision >
template<>
struct MD5Sum< ::itr_rpc::PointCollisionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::itr_rpc::PointCollision >::value();
  }
  static const char* value(const ::itr_rpc::PointCollisionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::itr_rpc::PointCollisionResponse> should match
// service_traits::DataType< ::itr_rpc::PointCollision >
template<>
struct DataType< ::itr_rpc::PointCollisionResponse>
{
  static const char* value()
  {
    return DataType< ::itr_rpc::PointCollision >::value();
  }
  static const char* value(const ::itr_rpc::PointCollisionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ITR_RPC_MESSAGE_POINTCOLLISION_H
