// Generated by gencpp from file itr_rpc/FK_Control.msg
// DO NOT EDIT!


#ifndef ITR_RPC_MESSAGE_FK_CONTROL_H
#define ITR_RPC_MESSAGE_FK_CONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace itr_rpc
{
template <class ContainerAllocator>
struct FK_Control_
{
  typedef FK_Control_<ContainerAllocator> Type;

  FK_Control_()
    : header()
    , configuration()  {
    }
  FK_Control_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , configuration(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _configuration_type;
  _configuration_type configuration;





  typedef boost::shared_ptr< ::itr_rpc::FK_Control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::itr_rpc::FK_Control_<ContainerAllocator> const> ConstPtr;

}; // struct FK_Control_

typedef ::itr_rpc::FK_Control_<std::allocator<void> > FK_Control;

typedef boost::shared_ptr< ::itr_rpc::FK_Control > FK_ControlPtr;
typedef boost::shared_ptr< ::itr_rpc::FK_Control const> FK_ControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::itr_rpc::FK_Control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::itr_rpc::FK_Control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::itr_rpc::FK_Control_<ContainerAllocator1> & lhs, const ::itr_rpc::FK_Control_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.configuration == rhs.configuration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::itr_rpc::FK_Control_<ContainerAllocator1> & lhs, const ::itr_rpc::FK_Control_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace itr_rpc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::itr_rpc::FK_Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::itr_rpc::FK_Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::itr_rpc::FK_Control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::itr_rpc::FK_Control_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::itr_rpc::FK_Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::itr_rpc::FK_Control_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::itr_rpc::FK_Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3bf0186665f4f6dd1e878e6232fdb43";
  }

  static const char* value(const ::itr_rpc::FK_Control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3bf0186665f4f6dULL;
  static const uint64_t static_value2 = 0xd1e878e6232fdb43ULL;
};

template<class ContainerAllocator>
struct DataType< ::itr_rpc::FK_Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "itr_rpc/FK_Control";
  }

  static const char* value(const ::itr_rpc::FK_Control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::itr_rpc::FK_Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Header must contain time stamp\n"
"Header header\n"
"\n"
"# Target configuration for kinematic controller\n"
"float32[] configuration\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::itr_rpc::FK_Control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::itr_rpc::FK_Control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.configuration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FK_Control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::itr_rpc::FK_Control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::itr_rpc::FK_Control_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "configuration[]" << std::endl;
    for (size_t i = 0; i < v.configuration.size(); ++i)
    {
      s << indent << "  configuration[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.configuration[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ITR_RPC_MESSAGE_FK_CONTROL_H
