// Generated by gencpp from file itr_rpc/LineCollisionRequest.msg
// DO NOT EDIT!


#ifndef ITR_RPC_MESSAGE_LINECOLLISIONREQUEST_H
#define ITR_RPC_MESSAGE_LINECOLLISIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace itr_rpc
{
template <class ContainerAllocator>
struct LineCollisionRequest_
{
  typedef LineCollisionRequest_<ContainerAllocator> Type;

  LineCollisionRequest_()
    : header()
    , start()
    , goal()  {
      start.assign(0.0);

      goal.assign(0.0);
  }
  LineCollisionRequest_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , start()
    , goal()  {
  (void)_alloc;
      start.assign(0.0);

      goal.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<float, 3>  _start_type;
  _start_type start;

   typedef boost::array<float, 3>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::itr_rpc::LineCollisionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::itr_rpc::LineCollisionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LineCollisionRequest_

typedef ::itr_rpc::LineCollisionRequest_<std::allocator<void> > LineCollisionRequest;

typedef boost::shared_ptr< ::itr_rpc::LineCollisionRequest > LineCollisionRequestPtr;
typedef boost::shared_ptr< ::itr_rpc::LineCollisionRequest const> LineCollisionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::itr_rpc::LineCollisionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::itr_rpc::LineCollisionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::itr_rpc::LineCollisionRequest_<ContainerAllocator1> & lhs, const ::itr_rpc::LineCollisionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.start == rhs.start &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::itr_rpc::LineCollisionRequest_<ContainerAllocator1> & lhs, const ::itr_rpc::LineCollisionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace itr_rpc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::itr_rpc::LineCollisionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::itr_rpc::LineCollisionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::itr_rpc::LineCollisionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::itr_rpc::LineCollisionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::itr_rpc::LineCollisionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::itr_rpc::LineCollisionRequest_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::itr_rpc::LineCollisionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "503139a359801d22d1f8b49513490455";
  }

  static const char* value(const ::itr_rpc::LineCollisionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x503139a359801d22ULL;
  static const uint64_t static_value2 = 0xd1f8b49513490455ULL;
};

template<class ContainerAllocator>
struct DataType< ::itr_rpc::LineCollisionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "itr_rpc/LineCollisionRequest";
  }

  static const char* value(const ::itr_rpc::LineCollisionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::itr_rpc::LineCollisionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Header must contain time stamp\n"
"Header header\n"
"\n"
"# Target line between two points start and goal\n"
"float32[3] start\n"
"float32[3] goal\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::itr_rpc::LineCollisionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::itr_rpc::LineCollisionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.start);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LineCollisionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::itr_rpc::LineCollisionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::itr_rpc::LineCollisionRequest_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "start[]" << std::endl;
    for (size_t i = 0; i < v.start.size(); ++i)
    {
      s << indent << "  start[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.start[i]);
    }
    s << indent << "goal[]" << std::endl;
    for (size_t i = 0; i < v.goal.size(); ++i)
    {
      s << indent << "  goal[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.goal[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ITR_RPC_MESSAGE_LINECOLLISIONREQUEST_H
