// Generated by gencpp from file itr_rpc/PointCollisionRequest.msg
// DO NOT EDIT!


#ifndef ITR_RPC_MESSAGE_POINTCOLLISIONREQUEST_H
#define ITR_RPC_MESSAGE_POINTCOLLISIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace itr_rpc
{
template <class ContainerAllocator>
struct PointCollisionRequest_
{
  typedef PointCollisionRequest_<ContainerAllocator> Type;

  PointCollisionRequest_()
    : header()
    , position()  {
      position.assign(0.0);
  }
  PointCollisionRequest_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position()  {
  (void)_alloc;
      position.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<float, 3>  _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::itr_rpc::PointCollisionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::itr_rpc::PointCollisionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PointCollisionRequest_

typedef ::itr_rpc::PointCollisionRequest_<std::allocator<void> > PointCollisionRequest;

typedef boost::shared_ptr< ::itr_rpc::PointCollisionRequest > PointCollisionRequestPtr;
typedef boost::shared_ptr< ::itr_rpc::PointCollisionRequest const> PointCollisionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::itr_rpc::PointCollisionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::itr_rpc::PointCollisionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::itr_rpc::PointCollisionRequest_<ContainerAllocator1> & lhs, const ::itr_rpc::PointCollisionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::itr_rpc::PointCollisionRequest_<ContainerAllocator1> & lhs, const ::itr_rpc::PointCollisionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace itr_rpc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::itr_rpc::PointCollisionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::itr_rpc::PointCollisionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::itr_rpc::PointCollisionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::itr_rpc::PointCollisionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::itr_rpc::PointCollisionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::itr_rpc::PointCollisionRequest_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::itr_rpc::PointCollisionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d638e8cbc0ea2d6e7cca0c66761a4b1";
  }

  static const char* value(const ::itr_rpc::PointCollisionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d638e8cbc0ea2d6ULL;
  static const uint64_t static_value2 = 0xe7cca0c66761a4b1ULL;
};

template<class ContainerAllocator>
struct DataType< ::itr_rpc::PointCollisionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "itr_rpc/PointCollisionRequest";
  }

  static const char* value(const ::itr_rpc::PointCollisionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::itr_rpc::PointCollisionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Header must contain time stamp\n"
"Header header\n"
"\n"
"# Target position\n"
"float32[3] position\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::itr_rpc::PointCollisionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::itr_rpc::PointCollisionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointCollisionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::itr_rpc::PointCollisionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::itr_rpc::PointCollisionRequest_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.position[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ITR_RPC_MESSAGE_POINTCOLLISIONREQUEST_H
